name: Unit Tests

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1

      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install Dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Code Style
        run: poetry run black . --check

      - name: Static Type check
        run: poetry run mypy yams

      - name: Linting
        run: |
          # stop the build if there are Python syntax errors or undefined names
          poetry run flake8 yams --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          poetry run flake8 yams --count --exit-zero --max-complexity=12 --max-line-length=88 --statistics

      - name: Test with pytest
        run: poetry run pytest --cov=yams --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
